<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 *
 * @author        Julio Reis <julio.reis@e-smart.com.br>
 */

class BSeller_SkyHub_Block_Adminhtml_Customer_Attributes_Mapping_Renderer_LinkCreate extends Mage_Adminhtml_Block_Widget_Grid_Column_Renderer_Abstract
{
    use BSeller_Core_Trait_Data;
    use BSeller_SkyHub_Trait_Attribute_Notification;

    public function render(Varien_Object $row)
    {
        if(!$row->getAttributeId()) {
            $value = $this->getCustomerAttributeAutoUrl($row->getData('id'));
            $linkLabel = $this->__('Create Attribute');
            return '<a href="' . $value . '">' . $linkLabel . '</a>';
        }
        return '';
    }
}