<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types
    extends BSeller_Core_Model_System_Config_Source_Abstract
{

    const TYPE_NEW       = 'NEW';
    const TYPE_CANCELED  = 'CANCELED';
    const TYPE_APPROVED  = 'APPROVED';
    const TYPE_SHIPPED   = 'SHIPPED';
    const TYPE_DELIVERED = 'DELIVERED';


    /**
     * @return array
     */
    protected function optionsKeyValue()
    {
        return [
            self::TYPE_NEW       => $this->__('New'),
            self::TYPE_CANCELED  => $this->__('Canceled'),
            self::TYPE_APPROVED  => $this->__('Approved'),
            self::TYPE_SHIPPED   => $this->__('Shipped'),
            self::TYPE_DELIVERED => $this->__('Delivered'),
        ];
    }
}
