<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Integrator_Middleware_Catalog_Product_Attribute
    extends BSeller_SkyHub_Model_Integrator_Middleware_Abstract
{
    
    public function update(Mage_Eav_Model_Entity_Attribute $attribute)
    {
        return $this->integrator()->update($attribute);
    }
    
    
    public function create(Mage_Eav_Model_Entity_Attribute $attribute)
    {
        return $this->integrator()->create($attribute);
    }
    
    
    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Product_Attribute
     */
    public function integrator()
    {
        return $this->catalogProductAttributeIntegrator();
    }
}
