<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Processor_Sales_Order_Status extends BSeller_SkyHub_Model_Integrator_Abstract
{
    use BSeller_SkyHub_Trait_Queue;
    /**
     * @param string                 $skyhubStatusCode
     * @param string                 $skyhubStatusType
     * @param Mage_Sales_Model_Order $order
     *
     * @return bool|$this
     */
    public function processOrderStatus($skyhubStatusCode, $skyhubStatusType, Mage_Sales_Model_Order $order)
    {
        if (!$this->validateOrderStatusType($skyhubStatusType)) {
            return false;
        }

        $state = $this->getStateBySkyhubStatusType($skyhubStatusType);

        if ($order->getState() == $state) {
            return false;
        }

        /**
         * Order is already in the following states:
         *  - complete
         *  - closed
         */
        if ($order->isStateProtected($state)) {
            /** State is protected. */
            return false;
        }

        /**
         * If order is CANCELED in SkyHub.
         */
        if ($state == Mage_Sales_Model_Order::STATE_CANCELED) {
            try {
                $this->cancelOrder($order);
            } catch (Exception $e) {
                return false;
            }

            return true;
        }

        if ($order->hasInvoices() && !$order->canInvoice()) {
            return true;
        }

        /**
         * If order is APPROVED in SkyHub.
         */
        if ($state == Mage_Sales_Model_Order::STATE_PROCESSING && $order->canInvoice()) {
            try {
                $this->invoiceOrder($order);
            } catch (Exception $e) {
                $order->addStatusHistoryComment('Error to invoice order: ' . $e->getMessage(), true);
                Mage::logException($e);
                return false;
            }

            return true;
        }

        $message = $this->__(
            'Change automatically by SkyHub. Status %s, Type %s.',
            $skyhubStatusCode,
            $skyhubStatusType
        );

        $order->setState($state, true, $message);
        $order->save();

        return true;
    }


    /**
     * @param string $skyhubStatusType
     *
     * @return string
     */
    public function getStateBySkyhubStatusType($skyhubStatusType)
    {
        switch ($skyhubStatusType) {
            case BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types::TYPE_APPROVED:
                return Mage_Sales_Model_Order::STATE_PROCESSING;
            case BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types::TYPE_CANCELED:
                return Mage_Sales_Model_Order::STATE_CANCELED;
            case BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types::TYPE_DELIVERED:
            case BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types::TYPE_SHIPPED:
                return Mage_Sales_Model_Order::STATE_COMPLETE;
            case BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types::TYPE_NEW:
            default:
                return Mage_Sales_Model_Order::STATE_NEW;
        }
    }


    /**
     * @param string $skyhubStatusType
     *
     * @return bool
     */
    public function validateOrderStatusType($skyhubStatusType)
    {
        /** @var BSeller_SkyHub_Model_System_Config_Source_Skyhub_Status_Types $source */
        $source = Mage::getModel('bseller_skyhub/system_config_source_skyhub_status_types');
        $allowedTypes = $source->toArray();

        return isset($allowedTypes[$skyhubStatusType]);
    }


    /**
     * @param Mage_Sales_Model_Order $order
     *
     * @return bool
     *
     * @throws Exception
     */
    protected function cancelOrder(Mage_Sales_Model_Order $order)
    {
        if (!$order->canCancel()) {
            $order->addStatusHistoryComment(
                $this->__('Order is canceled in SkyHub but could not be canceled in Magento.')
            );

            $order->save();

            return false;
        }

        $order->addStatusHistoryComment($this->__('Order canceled automatically by SkyHub.'));

        $order->cancel()->save();

        return true;
    }


    /**
     * @param Mage_Sales_Model_Order $order
     *
     * @return bool
     *
     * @throws Exception
     */
    protected function invoiceOrder(Mage_Sales_Model_Order $order)
    {
        if (!$order->canInvoice()) {
            $comment = $this->__('This order is APPROVED in SkyHub but cannot be invoiced in Magento.');
            $order->addStatusHistoryComment($comment, true);
            $order->save();

            return false;
        }

        /** @var Mage_Sales_Model_Order_Invoice $invoice */
        $invoice = $order->prepareInvoice();
        $invoice->register();

        $comment = $this->__('Invoiced automatically via SkyHub.');
        $invoice->addComment($comment);

        $order->setIsInProcess(true);
        $order->setStatus($this->getApprovedOrdersStatus());
        $order->addStatusHistoryComment($comment, true);

        /** @var Mage_Core_Model_Resource_Transaction $transaction */
        $transaction = Mage::getResourceModel('core/transaction');
        $transaction->addObject($order)
            ->addObject($invoice)
            ->save();

        return true;
    }
}
