<?php

/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BitTools
 * @package   BitTools_ModuleName
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */
class BSeller_SkyHub_Test_Model_Functional_Product_Mapping extends BSeller_SkyHub_Test_AbstractTest
{
    use BSeller_SkyHub_Trait_Catalog_Product_Attribute;

    public function setUp()
    {
        parent::setUp();
    }

    public function testMapProductAttribute()
    {
        //height attribute id
        $id = 10;

        //testing if the module can create and atach automatically an atribute;
        /** @var BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping $mapping */
        $mapping = $this->getMapping($id);

        $config = array(
            'label' => $mapping->getSkyhubLabel(),
            'type' => 'varchar',
            'input' => 'text',
            'required' => 0,
            'visible_on_front' => 0,
            'filterable' => 0,
            'searchable' => 0,
            'comparable' => 0,
            'user_defined' => 1,
            'is_configurable' => 0,
            'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
            'note' => sprintf(
                '%s. %s.',
                'Created automatically by BSeller SkyHub module.',
                $mapping->getSkyhubDescription()
            ),
        );

        $installConfig = (array)$mapping->getAttributeInstallConfig();

        foreach ($installConfig as $configKey => $itemValue) {
            if (is_null($itemValue)) {
                continue;
            }

            $config[$configKey] = $itemValue;
        }

        /** @var Mage_Eav_Model_Entity_Attribute $attribute */
        $attribute = $this->createProductAttribute($mapping->getSkyhubCode(), (array)$config);

        $mapping->setAttributeId((int)$attribute->getId())
            ->save();

        $this->assertNotNull($mapping->getAttributeId());
    }

    protected function getMapping($id)
    {
        /** @var BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping $mapping */
        $mapping = Mage::getModel('bseller_skyhub/catalog_product_attributes_mapping');
        $mapping->load((int) $id);

        Mage::register('current_attributes_mapping', $mapping, true);

        return $mapping;
    }

    public function tearDown()
    {
        //removing the EAV attribute created for testing;
        $attribute = Mage::getModel('eav/entity_attribute')->loadByCode(Mage_Catalog_Model_Product::ENTITY, 'height');
        $attribute->delete();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}