<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Cron_Catalog_Product extends BSeller_SkyHub_Model_Cron_Abstract
{

    /**
     * @param Mage_Cron_Model_Schedule $schedule
     */
    public function createProductsQueue(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->canRun($schedule)) {
            return;
        }

        $queuedIds = (array) $this->getQueueResource()
            ->getPendingEntityIds(BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT);

        $queuedIds = $this->filterIds($queuedIds);

        /** @var Mage_Catalog_Model_Resource_Product_Collection $collection */
        $collection = $this->getProductCollection()
            ->addAttributeToFilter('visibility', [
                'neq' => Mage_Catalog_Model_Product_Visibility::VISIBILITY_NOT_VISIBLE
            ]);

        if (!empty($queuedIds)) {
            $collection->addFieldToFilter('entity_id', ['nin' => $queuedIds]);
        }

        /** @var Varien_Db_Select $select */
        $select = $collection->getSelect()
            ->reset('columns')
            ->columns('entity_id')
            ->order('updated_at DESC')
            ->order('created_at DESC')
        ;

        /**
         * Set limitation.
         */
        $limit = $this->getCronConfig()->catalogProduct()->getQueueExecuteLimit();
        if ($limit) {
            $select->limit((int) $limit);
        }

        $productIds = (array) $this->getQueueResource()->getReadConnection()->fetchCol($select);

        if (empty($productIds)) {
            $schedule->setMessages($this->__('No products to be queued this time.'));
            return;
        }

        $this->getQueueResource()->queue($productIds, BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT);

        $schedule->setMessages(
            $this->__('%s product(s) were queued. IDs: %s.', count($productIds), implode(',', $productIds))
        );
    }


    /**
     * @param Mage_Cron_Model_Schedule $schedule
     */
    public function executeProductsQueue(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->canRun($schedule)) {
            return;
        }

        $productIds = (array) $this->getQueueResource()
            ->getPendingEntityIds(BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT);

        $productIds = $this->filterIds($productIds);

        /** @var Mage_Catalog_Model_Resource_Product_Collection $collection */
        $collection = $this->getProductCollection()
            ->addFieldToFilter('entity_id', ['in' => $productIds]);

        /**
         * Set limitation.
         */
        $limit = $this->getCronConfig()->catalogProduct()->getQueueExecuteLimit();
        if ($limit) {
            $collection->getSelect()->limit((int) $limit);
        }

        if (!$collection->getSize()) {
            $schedule->setMessages($this->__('No product to be integrated this time.'));
            return;
        }

        $successIds = [];
        $errorIds   = [];

        /** @var Mage_Catalog_Model_Product $product */
        foreach ($collection as $product) {
            /** @var \SkyHub\Api\Handler\Response\HandlerInterface $response */
            $response = $this->catalogProductIntegrator()->createOrUpdate($product);

            if ($this->isErrorResponse($response)) {
                $errorIds[] = $product->getId();

                /** @var \SkyHub\Api\Handler\Response\HandlerException $response */
                $this->getQueueResource()->setFailedEntityIds(
                    $product->getId(),
                    BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT,
                    $response->message()
                );
                continue;
            }

            $successIds[] = $product->getId();
        }

        if (!empty($successIds)) {
            $this->getQueueResource()
                ->removeFromQueue($successIds, BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT);
        }

        $schedule->setMessages($this->__(
            'Queue was processed. Success: %s. Errors: %s.',
            implode(',', $successIds),
            implode(',', $errorIds)
        ));
    }


    /**
     * @return Mage_Catalog_Model_Resource_Product_Collection
     */
    protected function getProductCollection()
    {
        /** @var Mage_Catalog_Model_Resource_Product_Collection $collection */
        $collection = Mage::getResourceModel('catalog/product_collection');
        return $collection;
    }


    /**
     * @param array $ids
     *
     * @return array
     */
    protected function filterIds(array $ids)
    {
        $ids = array_filter($ids, function (&$value) {
            $value = (int) $value;
            return $value;
        });

        return (array) $ids;
    }


    /**
     * @param Mage_Cron_Model_Schedule $schedule
     *
     * @return bool
     */
    protected function canRun(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->getCronConfig()->catalogProduct()->isEnabled()) {
            $schedule->setMessages($this->__('Catalog Product Cron is Disabled'));
            return false;
        }

        return parent::canRun($schedule);
    }
}
