<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */


class BSeller_SkyHub_Model_Observer_Sales_Order
{
    
    use BSeller_SkyHub_Trait_Data;
    
    
    /**
     * @param Varien_Event_Observer $observer
     */
    public function logOrderDetails(Varien_Event_Observer $observer)
    {
        if (true === Mage::registry('disable_order_log')) {
            return;
        }
        
        /**
         * @var Exception $exception
         * @var array     $orderData
         */
        $exception = $observer->getData('exception');
        $orderData = (array) $observer->getData('order_data');
        
        if (!$exception || !$orderData) {
            return;
        }
        
        $orderCode = $this->arrayExtract($orderData, 'code');
        
        $data = [
            'entity_id'       => null,
            'reference'       => (string) $orderCode,
            'entity_type'     => BSeller_SkyHub_Model_Entity::TYPE_SALES_ORDER,
            'status'          => BSeller_SkyHub_Model_Queue::STATUS_FAIL,
            'process_type'    => BSeller_SkyHub_Model_Queue::PROCESS_TYPE_IMPORT,
            'messages'        => $exception->getMessage(),
            'additional_data' => json_encode($orderData),
            'can_process'     => false,
            'store_id'        => (int) $this->getStoreId(),
        ];
        
        /** @var BSeller_SkyHub_Model_Queue $queue */
        $queue = Mage::getModel('bseller_skyhub/queue');
        $queue->setData($data);
        $queue->save();
    }
    
    
    /**
     * @return int
     *
     * @throws Mage_Core_Model_Store_Exception
     */
    protected function getStoreId()
    {
        return Mage::app()->getStore()->getId();
    }
}
