<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */
class BSeller_SkyHub_Block_Adminhtml_Sales_Plp_Grid
    extends BSeller_Core_Block_Adminhtml_Widget_Grid
{


    /**
     * @return Mage_Adminhtml_Block_Widget_Grid
     */
    protected function _prepareCollection()
    {
        /** @var BSeller_SkyHub_Model_Resource_Plp_Collection $collection */
        $collection = Mage::getResourceModel('bseller_skyhub/plp_collection');
        $this->setCollection($collection);
        return parent::_prepareCollection();
    }
    
    
    /**
     * @return $this
     *
     * @throws Exception
     */
    protected function _prepareColumns()
    {
        $this->addColumn(
            'skyhub_code',
            array(
                'header'           => $this->__('PLP Code'),
                'width'            => '250px',
                'align'            => 'left',
            )
        )
        ->addColumn(
            'created_at',
            array(
                'header'           => $this->__('Creation Date'),
                'type'             => 'date',
                'width'            => '250px',
                'align'            => 'left',
            )
        )
        ->addColumn(
            'expiration_date',
            array(
                'header'           => $this->__('Expiration Date'),
                'type'             => 'date',
                'width'            => '250px',
                'align'            => 'left',
            )
        );
        
        return parent::_prepareColumns();
    }
    
    
    /**
     * @param BSeller_SkyHub_Model_Plp $plp
     *
     * @return string|bool
     */
    public function getRowUrl($plp)
    {
        return $this->getUrl('*/*/view', ['id' => $plp->getId()]);
    }
}
