<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Observer_Integration
{

    use BSeller_SkyHub_Trait_Data,
        BSeller_SkyHub_Trait_Integrators,
        BSeller_SkyHub_Model_Integrator_Catalog_Product_Validation;


    /**
     * @param Varien_Event_Observer $observer
     */
    public function updateProductAttribute(Varien_Event_Observer $observer)
    {
        /** @var Mage_Catalog_Model_Resource_Eav_Attribute $attribute */
        $attribute = $observer->getData('attribute');

        if (!$attribute instanceof Mage_Catalog_Model_Resource_Eav_Attribute) {
            return;
        }

        /** @var BSeller_SkyHub_Model_Integrator_Catalog_Product_Attribute $processor */
        $processor = $this->catalogProductAttributeIntegrator();

        /**
         * Call method according to product attribute's operation: update or creation.
         */
        if ($attribute->getOrigData('attribute_code')) {
            /** Attribute is being updated. */
            $processor->update($attribute);
            return;
        }

        /** Otherwise attribute is being created. */
        $processor->create($attribute);
    }
    
    
    public function addIntegrateButtonToProductEditPage(Varien_Event_Observer $observer)
    {
        /** @var Mage_Adminhtml_Block_Catalog_Product_Edit $block */
        $block = $observer->getData('block');
        
        if (!($block instanceof Mage_Adminhtml_Block_Catalog_Product_Edit)) {
            return;
        }
        
        $product = $block->getProduct();
        
        if (!$product || !($product instanceof Mage_Catalog_Model_Product)) {
            return;
        }
        
        if (!$this->canIntegrateProduct($product)) {
            return;
        }
    
        /** @var Mage_Adminhtml_Block_Widget_Button $backButton */
        $backButton = $block->getChild('back_button');
        
        if (!($backButton instanceof Mage_Adminhtml_Block_Widget_Button)) {
            return;
        }
        
        /** @var Mage_Adminhtml_Block_Widget_Button $button */
        $button = $block->getLayout()->createBlock('adminhtml/widget_button');
        $button->setData([
             'label'   => Mage::helper('catalog')->__('Integrate With SkyHub'),
             'onclick' => "setLocation('{$this->getIntegrateUrl($block)}')",
             'class'   => 'success'
         ]);
    
        $backButton->setBeforeHtml($button->toHtml());
    }
    
    
    /**
     * @param Mage_Adminhtml_Block_Catalog_Product_Edit $block
     *
     * @return string
     */
    protected function getIntegrateUrl(Mage_Adminhtml_Block_Catalog_Product_Edit $block)
    {
        $url = (string) $block->getUrl('*/*/integrate', ['product_id' => $block->getProductId()]);
        return $url;
    }
}
