<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
trait BSeller_SkyHub_Model_Integrator_Catalog_Product_Validation
{
    
    /**
     * @param Mage_Catalog_Model_Product $product
     *
     * @return bool
     */
    public function canIntegrateProduct(Mage_Catalog_Model_Product $product)
    {
        if (!$product->getId()) {
            return false;
        }
        
        return true;
    }
    
}
