<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Integrator_Middleware_Catalog_Product
    extends BSeller_SkyHub_Model_Integrator_Middleware_Abstract
{

    /**
     * @param Mage_Catalog_Model_Product $product
     *
     * @return bool|\SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function update(Mage_Catalog_Model_Product $product)
    {
        $response = true;

        if ($this->canIntegrate($this->method())) {
            $response = $this->integrator()->update($product);
        } else {
            $this->queue($this->method(), $product->getId(), $this->entityType(), 'update');
        }

        return $response;
    }


    /**
     * @param Mage_Catalog_Model_Product $product
     *
     * @return bool|\SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function create(Mage_Catalog_Model_Product $product)
    {
        $response = true;

        if ($this->canIntegrate($this->method())) {
            $response = $this->integrator()->create($product);
        } else {
            $this->queue($this->method(), $product->getId(), $this->entityType(), 'create');
        }

        return $response;
    }
    
    
    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Product
     */
    public function integrator()
    {
        return $this->catalogProductIntegrator();
    }


    /**
     * @return string
     */
    public function method()
    {
        return $this->getCatalogProductIntegrationMethod();
    }


    /**
     * @return string
     */
    public function entityType()
    {
        return BSeller_SkyHub_Model_Queue::ENTITY_TYPE_CATALOG_PRODUCT;
    }
}
