<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_System_Config_Source_Sales_Order_Status_Complete
    extends Mage_Adminhtml_Model_System_Config_Source_Order_Status
{
    
    protected $_stateStatuses = Mage_Sales_Model_Order::STATE_COMPLETE;
    
    
    /**
     * @return array
     */
    public function toOptionArray()
    {
        $options = parent::toOptionArray();
        
        foreach ($options as $idx => $option) {
            if ($option['value'] == 'complete') {
                unset($options[$idx]);
                break;
            }
        }
        
        return $options;
    }
}
