<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Cron_Queue_Sales_Order_Queue extends BSeller_SkyHub_Model_Cron_Queue_Sales_Abstract
{

    /**
     * Import next orders from the queue in SkyHub.
     *
     * @param Mage_Cron_Model_Schedule $schedule
     */
    public function execute(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->canRun($schedule)) {
            return;
        }

        $limit = 20;
        $count = 0;

        while ($count < $limit) {
            /** @var \SkyHub\Api\Handler\Response\HandlerDefault $result */
            //$orderData = $this->orderQueueIntegrator()->nextOrder();
            $orderData = json_decode('{
    "updated_at": "2018-03-29T11:28:29-03:00",
    "total_ordered": 59.54,
    "tags": [
    ],
    "sync_status": "SYNCED",
    "status": {
        "type": "APPROVED",
        "label": "Aguardando estoque disponível no WMS",
        "code": "AEF"
    },
    "shipping_method": "Std BR Dom 4",
    "shipping_cost": 9.64,
    "shipping_carrier": "",
    "shipping_address": {
        "street": "andirá",
        "secondary_phone": null,
        "region": "SP",
        "reference": null,
        "postcode": "09175100",
        "phone": "11997063902",
        "number": "N/A",
        "neighborhood": "N/A",
        "full_name": "MARCOS ROCHA",
        "detail": "72",
        "country": "BR",
        "city": "Santo André"
    },
    "shipped_date": "",
    "shipments": [
    ],
    "placed_at": "2018-03-29T11:00:42-03:00",
    "payments": [
    ],
    "items": [
        {
            "special_price": 49.9,
            "qty": 1,
            "product_id": "julioteste",
            "original_price": 49.9,
            "name": "Balança Digital 200Kg G-Tech Com Plataforma de Vidro Temperado, Visor LCD de Fácil Visualização e Desligamento Automático - Glass 200",
            "id": "julioteste"
        }
    ],
    "invoices": [
    ],
    "interest": 0,
    "import_info": {
        "remote_id": null,
        "remote_code": "701-4967088-8565849"
    },
    "estimated_delivery_shift": null,
    "estimated_delivery": "2018-04-17T23:59:59-03:00",
    "discount": 0,
    "customer": {
        "vat_number": "11120716870",
        "phones": [
            "11997063902"
        ],
        "name": "Cristiane de souza cale da rocha",
        "gender": "",
        "email": "lkwwmcf4g18s3yq@marketplace.amazon.com.br",
        "date_of_birth": null
    },
    "code": "Amazon-701-4967088-8565849",
    "channel": "Amazon",
    "calculation_type": null,
    "billing_address": {
        "street": "andirá",
        "secondary_phone": null,
        "region": "SP",
        "reference": null,
        "postcode": "09175100",
        "phone": "11997063902",
        "number": "N/A",
        "neighborhood": "N/A",
        "full_name": "MARCOS ROCHA",
        "detail": "72",
        "country": "BR",
        "city": "Santo André"
    },
    "approved_date": "2018-03-29T14:30:43.244000"
}', true);

            if (empty($orderData)) {
                $schedule->setMessages($this->__('No order found in the queue.'));
                break;
            }

            try {
                /** @var Mage_Sales_Model_Order $order */
                $order = $this->salesOrderProcessor()->createOrder($orderData);
            } catch (Exception $e) {
                /** The log is already created in the createOrder method. */
                continue;
            }

            if (!$order || !$order->getId()) {
                $schedule->setMessages($this->__('Order cannot be created.'));
                return;
            }

            $message  = $schedule->getMessages();
            $message .= $this->__('Order %s successfully created.', $order->getIncrementId());

            /** @var \SkyHub\Api\Handler\Response\HandlerDefault $isDeleted */
            $isDeleted = $this->orderQueueIntegrator()->deleteByOrder($order);
            
            if ($isDeleted) {
                $message .= ' ' . $this->__('It was also removed from queue.');
            }

            $schedule->setMessages($message);
            $count++;
        }
    }

    
    /**
     * @param Mage_Cron_Model_Schedule $schedule
     *
     * @return bool
     */
    protected function canRun(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->getCronConfig()->salesOrderQueue()->isEnabled()) {
            $schedule->setMessages($this->__('Sales Order Queue Cron is Disabled'));
            return false;
        }
        
        return parent::canRun($schedule);
    }
}
