<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Cron_Queue_Sales_Order_Queue extends BSeller_SkyHub_Model_Cron_Queue_Sales_Abstract
{

    /**
     * Import next orders from the queue in SkyHub.
     *
     * @param Mage_Cron_Model_Schedule $schedule
     */
    public function execute(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->canRun($schedule)) {
            return;
        }

        $limit = 20;
        $count = 0;

        while ($count < $limit) {
            /** @var \SkyHub\Api\Handler\Response\HandlerDefault $result */
            //$orderData = $this->orderQueueIntegrator()->nextOrder();

            $orderData = json_decode('{
  "updated_at": "2018-04-11T15:43:22-03:00",
  "total_ordered": 629.8,
  "tags": [
    
  ],
  "sync_status": "SYNCED",
  "status": {
    "type": "APPROVED",
    "label": "Aprovado",
    "code": "aprovado"
  },
  "shipping_method": "Entrega Econômica",
  "shipping_cost": 29.9,
  "shipping_carrier": "JadLog Standard",
  "shipping_address": {
    "street": "Alameda Jaú",
    "secondary_phone": null,
    "region": "SP",
    "reference": "Próximo ao Hotel Renassence",
    "postcode": "01420006",
    "phone": "11 30959890",
    "number": "1742",
    "neighborhood": "Jardim Paulista",
    "full_name": "Midia do Brasil Comunicações, serviços de televisão ltda",
    "detail": "1º andar - cj. 12 - Próximo ao Hotel Renassence",
    "country": "BR",
    "city": "Sao Paulo"
  },
  "shipped_date": "",
  "shipments": [
    
  ],
  "placed_at": "2018-04-11T15:33:02-03:00",
  "payments": [
    {
      "value": 629.8,
      "status": null,
      "parcels": 3,
      "method": "CREDIT_CARD",
      "description": "No valor de: 629.8"
    }
  ],
  "items": [
    {
      "special_price": 599.9,
      "qty": 1,
      "product_id": "julioteste",
      "original_price": 599.9,
      "name": "TV LED 19,5\" LG 20MT49DF-PS HD com Conversor Digital 1 HDMI 1 USB 60Hz Time Machine Ready Preta",
      "id": "julioteste"
    }
  ],
  "invoices": [
    
  ],
  "interest": 0,
  "import_info": {
    "remote_id": "01-68344470",
    "remote_code": "106834447001"
  },
  "estimated_delivery_shift": null,
  "estimated_delivery": "2018-04-25T00:00:00-03:00",
  "discount": 0,
  "customer": {
    "vat_number": "71841282000106",
    "state_registration": "114230680113",
    "phones": [
      "11 30959890"
    ],
    "name": "Midia do Brasil Comunicações, serviços de televisão ltda",
    "gender": "",
    "email": "71841282000106@email.com.br",
    "date_of_birth": null
  },
  "code": "Shoptime-106834447001",
  "channel": "Shoptime",
  "calculation_type": "intelipost",
  "billing_address": {
    "street": "Alameda Jaú",
    "secondary_phone": null,
    "region": "SP",
    "reference": "Próximo ao Hotel Renassence",
    "postcode": "01420006",
    "phone": "11 30959890",
    "number": "1742",
    "neighborhood": "Jardim Paulista",
    "full_name": "Midia do Brasil Comunicações, serviços de televisão ltda",
    "detail": "1º andar - cj. 12 - Próximo ao Hotel Renassence",
    "country": "BR",
    "city": "Sao Paulo"
  },
  "approved_date": "2018-04-11T18:52:45.327000"
}', true);

            if (empty($orderData)) {
                $schedule->setMessages($this->__('No order found in the queue.'));
                break;
            }

            try {
                /** @var Mage_Sales_Model_Order $order */
                $order = $this->salesOrderProcessor()->createOrder($orderData);
            } catch (Exception $e) {
                /** The log is already created in the createOrder method. */
                continue;
            }

            if (!$order || !$order->getId()) {
                $schedule->setMessages($this->__('Order cannot be created.'));
                return;
            }

            $message  = $schedule->getMessages();
            $message .= $this->__('Order %s successfully created.', $order->getIncrementId());

            /** @var \SkyHub\Api\Handler\Response\HandlerDefault $isDeleted */
            $isDeleted = $this->orderQueueIntegrator()->deleteByOrder($order);
            
            if ($isDeleted) {
                $message .= ' ' . $this->__('It was also removed from queue.');
            }

            $schedule->setMessages($message);
            $count++;
        }
    }
    
    
    /**
     * @param Mage_Cron_Model_Schedule $schedule
     *
     * @return bool
     */
    protected function canRun(Mage_Cron_Model_Schedule $schedule)
    {
        if (!$this->getCronConfig()->salesOrderQueue()->isEnabled()) {
            $schedule->setMessages($this->__('Sales Order Queue Cron is Disabled'));
            return false;
        }
        
        return parent::canRun($schedule);
    }
}
