<?php


/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Resource_Setup extends BSeller_Core_Model_Resource_Setup
{
    
    use BSeller_SkyHub_Trait_Config;
    
    
    /**
     * @return array
     */
    public function getSkyHubFixedAttributes()
    {
        return $this->getSkyHubConfig()->getSkyHubFixedAttributes();
    }
    
    
    /**
     * @return $this
     */
    public function installSkyHubRequiredAttributes()
    {
        $attributes = (array) $this->getSkyHubFixedAttributes();
        
        /** @var array $attribute */
        foreach ($attributes as $skyhubCode => $attribute) {
            $sku = $attribute['sku'];
            $label = $attribute['sku'];
            $type = $attribute['sku'];
            $description = $attribute['sku'];
            $validation = $attribute['sku'];
            $magentoCode = $attribute['sku'];
        }
        
        return $this;
    }
}
