<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Adminhtml_Bseller_Skyhub_Catalog_Product_Attributes_MappingController
    extends BSeller_SkyHub_Controller_Admin_Action
{
    
    /**
     * @return $this
     */
    protected function init()
    {
        parent::init();
        $this->_title($this->__('Product'));
        return $this;
    }
    
    
    /**
     * Attributes Mapping Grid Action.
     */
    public function indexAction()
    {
        $this->init();
        
        $this->_title($this->__('Attributes Mapping'));
        $this->_setActiveMenu('bseller/bseller_skyhub/catalog_product_attributes_mapping/grid');
        
        $this->renderLayout();
    }
    
    
    /**
     * Attributes Mapping Edit Action.
     */
    public function editAction()
    {
        $this->init();
    
        $id = $this->getRequest()->getParam('id', null);
    
        /** @var BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping $mapping */
        $mapping = $this->getMapping($id);
        
        if (!$mapping->getId()) {
            $this->_getSession()->addError($this->__('This mapping does not exist anymore.'));
            $this->_redirect('*/*');
            return;
        }
        
        $this->_title($this->__('Attributes Mapping Edit'));
        $this->_setActiveMenu('bseller/bseller_skyhub/catalog_product_attributes_mapping/grid');
    
        $this->renderLayout();
    }
    
    
    /**
     * @param int $id
     *
     * @return BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping
     */
    protected function getMapping($id)
    {
        /** @var BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping $mapping */
        $mapping = Mage::getModel('bseller_skyhub/catalog_product_attributes_mapping');
        $mapping->load((int) $id);
        
        Mage::register('current_attributes_mapping', $mapping, true);
        
        return $mapping;
    }

}
