<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

class BSeller_SkyHub_Block_Adminhtml_Shipment_Plp_View_File extends Mage_Adminhtml_Block_Template
{

    use BSeller_SkyHub_Trait_Service;
    use BSeller_SkyHub_Trait_Integrators;


    protected function _toHtml()
    {
        $this->getPlpFile();
        return parent::_toHtml();
    }


    /**
     * Get PLP file and save it in class object
     */
    public function getPlpFile()
    {
        /** @var BSeller_SkyHub_Model_Shipment_Plp $plp */
        $plp        = $this->getPlp();
        $fileFormat = $this->_getPlpFileFormat();

//        $fileFormat

        $file = $this->shipmentPlpIntegrator()->viewFile($plp);
        $this->_setFileContent($file);
    }


    /**
     * @param $jsonFile
     */
    protected function _setFileContent($jsonFile)
    {
        $formattedValue = json_decode($jsonFile, true);
        $formattedValue = json_encode($formattedValue, JSON_PRETTY_PRINT);
        $this->setFileContent($formattedValue);
    }


    /**
     * @return BSeller_SkyHub_Model_Shipment_Plp
     */
    public function getPlp()
    {
        /** @var BSeller_SkyHub_Model_Shipment_Plp $plp */
        $plp = Mage::registry('current_plp');

        if (!$plp) {
            $plp = Mage::getModel('bseller_skyhub/shipment_plp');
        }

        return $plp;
    }


    /**
     * @return string
     */
    protected function _getPlpFileFormat()
    {
        /** @var string $format */
        $format = Mage::registry('current_plp_file_format');

        if (!$format) {
            $format = '';
        }

        return $format;
    }

}