<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

class BSeller_SkyHub_Adminhtml_Bseller_Skyhub_Catalog_Product_EntityController extends BSeller_SkyHub_Controller_Admin_Action
{

    /**
     * Delete 'catalog_product' rows from BSeller SkyHub entity table
     */
    public function resetEntityAction()
    {
        try {
            Mage::getResourceModel('bseller_skyhub/entity')->truncateEntityType('catalog_product');
            $this->_getSession()->addSuccess(Mage::helper('adminhtml')->__('The product integration entity table has been cleared.'));
        } catch (Mage_Core_Exception $e) {
            $this->_getSession()->addError($e->getMessage());
        } catch (Exception $e) {
            $this->_getSession()->addException($e, Mage::helper('adminhtml')->__('An error occurred while clearing product integration entity table.'));
        }

        $this->getResponse()->setRedirect(Mage::helper('core/http')->getHttpReferer());
    }
}
