<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

class BSeller_SkyHub_Adminhtml_Bseller_Skyhub_Catalog_Product_MassQueueController
    extends BSeller_SkyHub_Controller_Admin_Action
{
    /**
     * Add product to queue
     *
     * @return void
     */
    public function addProductToQueueAction()
    {
        $products = $this->getRequest()->getParam('product', null);
        if(!is_array($products)) {
            $this->_redirect('*/catalog_product/index/');
        }

        $success = false;
        foreach ($products as $productId) {
            $product = Mage::getModel('catalog/product')->load($productId);
            /** @var BSeller_SkyHub_Model_Queue_Product $modelQueue */
            $modelQueue = Mage::getModel('bseller_skyhub/queue_product');
            if ($modelQueue->addToQueue($product)) {
                $success = true;
            }
        }

        if ($success) {
            $this->_getSession()
                ->addSuccess(
                    $this->__(
                        'Product add to queue with success. The queue are execute to cron.'
                    )
                );
        } else {
            $this->_getSession()
                ->addError(
                    $this->__(
                        'There was a problem when trying to add product the Queue.'
                    )
                );
        }
        
        $this->_redirect('*/catalog_product/index/');
    }
}
