<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

interface BSeller_SkyHub_Model_Store_Iterator_Interface
{
    
    /**
     * @return array
     */
    public function getStores();
    
    
    /**
     * @param string $class
     * @param string $object
     * @param array  $params
     *
     * @return $this
     */
    public function iterate($object, $method, array $params = []);
    
    
    /**
     * @return boolean
     */
    public function isIterating();
}
