<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Config_Cron
{

    /**
     * @param string $field
     *
     * @return string|integer
     */
    protected function getCronConfig($field)
    {
        return $this->getSkyHubModuleConfig($field, 'cron');
    }


    /**
     * @return bool
     */
    protected function isCronCatalogProductAttributesEnabled()
    {
        return (bool) $this->getCronConfig('catalog_product_attributes_queue_enabled');
    }


    /**
     * @return bool
     */
    protected function isCronCatalogProductsEnabled()
    {
        return (bool) $this->getCronConfig('catalog_products_queue_enabled');
    }


    /**
     * @param int $default
     *
     * @return bool
     */
    protected function getCatalogProductQueueExecuteLimit($default = 500)
    {
        $quantity = (int) $this->getCronConfig('catalog_products_queue_execute_limit');

        if (!$quantity) {
            $quantity = $default;
        }

        return (int) $quantity;
    }


    /**
     * @return bool
     */
    protected function isCronCatalogCategoriesEnabled()
    {
        return (bool) $this->getCronConfig('catalog_categories_queue_enabled');
    }
    
    
    /**
     * @return bool
     */
    protected function isCronSalesOrderQueueEnabled()
    {
        return (bool) $this->getCronConfig('sales_order_queue_import_enabled');
    }


    /**
     * @return bool
     */
    protected function isCronSalesOrderStatusEnabled()
    {
        return (bool) $this->getCronConfig('sales_order_status_queue_enabled');
    }
    
    
    /**
     * @return bool
     */
    protected function isCronSalesOrderEnabled()
    {
        return (bool) $this->getCronConfig('sales_order_update_enabled');
    }
}
