<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Julio Reis <julio.reis@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Config_General
{

    /**
     * @return BSeller_SkyHub_Model_Cron_Config
     */
    protected function getAddressSizeConfig()
    {
        return Mage::getStoreConfig('customer/address/street_lines');
    }
}
