<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Config_Service
{

    /**
     * @param string $field
     *
     * @return string|integer
     */
    protected function getServiceConfig($field)
    {
        return $this->getSkyHubModuleConfig($field, 'service');
    }


    /**
     * @return string
     */
    protected function getServiceBaseUri()
    {
        return (string) $this->getServiceConfig('base_uri');
    }


    /**
     * @return string
     */
    protected function getServiceEmail()
    {
        return (string) $this->getServiceConfig('email');
    }


    /**
     * @return string
     */
    protected function getServiceApiKey()
    {
        return (string) $this->getServiceConfig('api_key');
    }


    /**
     * @return string
     */
    protected function getServiceAccountManagerKey()
    {
        return (string) $this->getServiceConfig('account_manager_key');
    }


    /**
     * @return bool
     */
    protected function isConfigurationOk()
    {
        if (!$this->getServiceBaseUri()) {
            return false;
        }

        if (!$this->getServiceEmail()) {
            return false;
        }

        if (!$this->getServiceApiKey()) {
            return false;
        }

        if (!$this->getServiceAccountManagerKey()) {
            return false;
        }

        return true;
    }

}
