<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Shipping_Carrier_Standard extends Mage_Shipping_Model_Carrier_Freeshipping
{

    /** @var string */
    protected $_code = 'bseller_skyhub_standard';


    /**
     * FreeShipping Rates Collector
     *
     * @param Mage_Shipping_Model_Rate_Request $request
     *
     * @return Mage_Shipping_Model_Rate_Result|false
     */
    public function collectRates(Mage_Shipping_Model_Rate_Request $request)
    {
        if (!$this->getConfigFlag('active')) {
            return false;
        }
    
        $amount = 0;
        
        /** @var Mage_Sales_Model_Quote $quote */
        $quote = Mage::getSingleton('bseller_skyhub/adminhtml_session_quote')->getQuote();
        
        if ($quote) {
            $amount = $quote->getData('fixed_shipping_amount');
        }
        
        /** @var Mage_Shipping_Model_Rate_Result $result */
        $result = Mage::getModel('shipping/rate_result');

        /** @var Mage_Shipping_Model_Rate_Result_Method $method */
        $method = Mage::getModel('shipping/rate_result_method');

        $method->setCarrier('bseller_skyhub');
        $method->setCarrierTitle($this->getConfigData('title'));

        $method->setMethod('standard');
        $method->setMethodTitle($this->getConfigData('name'));
        
        $method->setPrice((float) $amount);
        $method->setCost(0.0000);

        $result->append($method);

        return $result;
    }

}
