<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Observer_Sales_Order_Status extends BSeller_SkyHub_Model_Observer_Abstract
{
    
    /**
     * @param Varien_Event_Observer $observer
     */
    public function processCompleteStatusOrder(Varien_Event_Observer $observer)
    {
        /** @var Mage_Sales_Model_Order $order */
        $order = $observer->getData('order');
        
        if (!$this->validateOrder($order)) {
            return;
        }
    
        $this->processShippingExceptionOrderStatus($order);
        $this->processDeliveredCustomerStatus($order);
    }
    
    
    /**
     * @param Mage_Sales_Model_Order $order
     *
     * @return $this
     */
    protected function processDeliveredCustomerStatus(Mage_Sales_Model_Order $order)
    {
        $configStatus = $this->getDeliveredOrdersStatus();
        
        if (!$this->statusMatches($configStatus, $order)) {
            return $this;
        }
        
        $this->orderIntegrator()->delivery($order->getId());
        
        return $this;
    }
    
    
    /**
     * @param Mage_Sales_Model_Order $order
     *
     * @return $this
     */
    protected function processShippingExceptionOrderStatus(Mage_Sales_Model_Order $order)
    {
        $configStatus = $this->getShipmentExceptionOrderStatus();
    
        if (!$this->statusMatches($configStatus, $order)) {
            return $this;
        }
    
        /**
         * @todo Check the correct format for this date time parameter.
         * @todo Turn the observation parameter as a flexible message (field in admin for instance).
         */
        $datetime    = date('Y:m:d H:i:s');
        $observation = $this->__('A problem has occurred with the order shipment.');
        
        $this->orderIntegrator()->shipmentException($order->getId(), $datetime, $observation);
        
        return $this;
    }
    
    
    /**
     * @param string                 $configStatus
     * @param Mage_Sales_Model_Order $order
     *
     * @return bool
     */
    protected function statusMatches($configStatus, Mage_Sales_Model_Order $order)
    {
        if ($order->getStatus() == $configStatus) {
            return true;
        }
        
        return false;
    }
    
    
    /**
     * @param Mage_Sales_Model_Order $order
     *
     * @return bool
     */
    protected function validateOrder(Mage_Sales_Model_Order $order)
    {
        if (!$order || !$order->getId()) {
            return false;
        }
    
        if ($order->getState() != Mage_Sales_Model_Order::STATE_COMPLETE) {
            return false;
        }
        
        return true;
    }
}
