<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Block_Adminhtml_Catalog_Product_Grid
    extends Mage_Adminhtml_Block_Catalog_Product_Grid
{
    protected function _prepareMassaction()
    {
        parent::_prepareMassaction();
        $this->getMassactionBlock()->addItem('add_product_queue_skyhub', array(
            'label'=> Mage::helper('catalog')->__('Add oriduct to Queue in Skyhub'),
            'url'  => $this->getUrl('*/bseller_skyhub_catalog_product_massQueue/addProductToQueue'),
            'confirm' => Mage::helper('catalog')->__('Are you sure?')
       ));
       return $this;
    }
}
