<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_System_Config_Source_Store_Available extends BSeller_Core_Model_System_Config_Source_Abstract
{
    
    use BSeller_SkyHub_Trait_Store_Iterator;
    
    
    /**
     * @return array
     */
    protected function optionsKeyValue($multiselect = null)
    {
        $stores = [];
        
        /** @var Mage_Core_Model_Store $store */
        foreach ($this->getStoreIterator()->getStores() as $store) {
            $stores[$store->getId()] = $store->getName();
        }
        
        return $stores;
    }
}
