<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
trait BSeller_SkyHub_Trait_Catalog_Product_Attribute
{
    
    /** @var Mage_Eav_Model_Resource_Entity_Attribute_Collection */
    protected $attributeCollection;
    
    /** @var array */
    protected $productAttributes = [];
    
    /** @var array */
    protected $entityTypes       = [];
    
    
    /**
     * @param string $attributeCode
     *
     * @return bool|Mage_Eav_Model_Entity_Attribute
     */
    protected function getAttributeByCode($attributeCode)
    {
        $this->initAttributeCollection();
        
        if (!isset($this->productAttributes[$attributeCode])) {
            return false;
        }
        
        return $this->productAttributes[$attributeCode];
    }
    
    
    /**
     * @return Mage_Eav_Model_Resource_Entity_Attribute_Collection
     */
    protected function initAttributeCollection()
    {
        if (!empty($this->attributeCollection)) {
            return $this->attributeCollection;
        }
        
        $entityType = $this->getEntityTypeId(Mage_Catalog_Model_Product::ENTITY);
        
        /** @var Mage_Eav_Model_Resource_Entity_Attribute_Collection $collection */
        $this->attributeCollection = Mage::getResourceModel('eav/entity_attribute_collection');
        $this->attributeCollection->setEntityTypeFilter($entityType->getId());
        
        /** @var Mage_Eav_Model_Entity_Attribute $attribute */
        foreach ($this->attributeCollection as $attribute) {
            $this->productAttributes[$attribute->getAttributeCode()] = $attribute;
        }
        
        return $this->attributeCollection;
    }
    
    
    /**
     * @return array
     */
    protected function getProductAttributes()
    {
        $this->initAttributeCollection();
        return $this->productAttributes;
    }
    
    
    /**
     * @param string $code
     *
     * @return Mage_Eav_Model_Entity_Type
     */
    protected function getEntityTypeId($code)
    {
        if (isset($this->entityTypes[$code])) {
            return $this->entityTypes[$code];
        }
        
        $type = Mage::getModel('eav/entity_type')->loadByCode($code);
        
        $this->entityTypes[$code] = $type;
        
        return $type;
    }
}
