<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Julio Reis <julio.reis@e-smart.com.br>
 */

/**
 * @var BSeller_SkyHub_Model_Resource_Setup $this
 * @var Magento_Db_Adapter_Pdo_Mysql        $conn
 */

$this->startSetup();

//**********************************************************************************************************************
// Update sales/order
//**********************************************************************************************************************
$columnName = 'integrate';
$tableName = $this->getTable('bseller_skyhub/entity_id');
$columnConfig = [
    'type' => $this::TYPE_INTEGER,
    'nullable' => false,
    'default' => false,
    'after' => '',
    'comment' => 'Product Flag',
];

$conn->addColumn($tableName, $columnName, $columnConfig);

$this->endSetup();
