<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Jefferson Porto <jefferson.porto@b2wdigital.com>
 */

$installer = new Mage_Core_Model_Resource_Setup('core_setup');
$installer->startSetup();

$data = array(
    array('BR', 'N/A', 'N/A'),
    array('BRA', 'N/A', 'N/A')
);

foreach ($data as $row) {
    $bind = array(
        'country_id' => $row[0],
        'code' => $row[1],
        'default_name' => $row[2],
    );
    $installer->getConnection()->insert($installer->getTable('directory/country_region'), $bind);
}

$installer->endSetup();