<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Julio Reis <julio.reis@e-smart.com.br>
 */

/**
 * @var BSeller_SkyHub_Model_Resource_Setup $this
 * @var Magento_Db_Adapter_Pdo_Mysql $conn
 */

$this->startSetup();

//dropping wrong index
$tableName = (string)$this->getTable('bseller_skyhub/entity_id');
$indexNameToDrop = $this->getIdxName($tableName, ['entity_id', 'entity_type']);
$sql = "DROP INDEX {$indexNameToDrop} ON {$tableName}";
$this->run($sql);

//recreating the index correctly
$this->addIndex(['entity_id', 'entity_type', 'store_id'], $tableName);

$this->endSetup();
