<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

/**
 * @var BSeller_SkyHub_Model_Resource_Setup $this
 * @var Magento_Db_Adapter_Pdo_Mysql        $conn
 */

$this->startSetup();


//**********************************************************************************************************************
// Install bseller_skyhub/plp
//**********************************************************************************************************************
$tableName = (string) $this->getTable('bseller_skyhub/plp');

/** @var Varien_Db_Ddl_Table $table */
$table = $this->newTable($tableName)
    ->addColumn(
        'bseller_skyhub_code',
        $this::TYPE_VARCHAR,
        30,
        [
            'nullable' => false,
        ]
    )
    ->addColumn(
        'expiration_date',
        $this::TYPE_DATE,
        null,
        [
            'nullable' => false,
        ]
    );

$this->addTimestamps($table);
$conn->createTable($table);

$this->addIndex(['bseller_skyhub_code'], $tableName);

$this->endSetup();
