<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Sales_Order
{


    /**
     * @return Mage_Sales_Model_Resource_Order_Collection
     */
    public function getPendingOrdersFromSkyHub()
    {
        $deniedStates = [
            Mage_Sales_Model_Order::STATE_CANCELED,
            Mage_Sales_Model_Order::STATE_CLOSED,
            Mage_Sales_Model_Order::STATE_COMPLETE,
        ];

        /** @var Mage_Sales_Model_Resource_Order_Collection $collection */
        $collection = Mage::getResourceModel('sales/order_collection');

        $collection ->addFieldToFilter('state', ['nin' => $deniedStates])
            ->addFieldToFilter('bseller_skyhub', 1);

        return $collection;
    }
}