<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Adminhtml_Bseller_Skyhub_ProductController extends BSeller_SkyHub_Controller_Admin_Action
{
    
    /**
     * @return $this
     */
    protected function init()
    {
        parent::init();
        $this->_title($this->__('Product'));
        return $this;
    }
    
    
    public function mapAttributesAction()
    {
        $this->init();
        $this->_title($this->__('Attributes Mapping'));
        $this->_setActiveMenu('bseller/bseller_skyhub/catalog_product_attributes/mapping');
        
        $this->renderLayout();
    }

}
