<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Adminhtml_Bseller_Skyhub_QueueController extends BSeller_SkyHub_Controller_Admin_Action
{
    
    /**
     * @return $this
     */
    protected function init()
    {
        parent::init();
        $this->_title($this->__('Queue'));
        return $this;
    }
    
    
    /**
     * Integration Pending Products
     */
    public function pendingProductsAction()
    {
        $this->init();
        $this->_title($this->__('Integration Pending Products'));
        $this->_setActiveMenu('bseller/bseller_skyhub/queues/pending_products');
        
        $this->renderLayout();
    }
    
    
    /**
     * Products With Integration Errors
     */
    public function errorProductsAction()
    {
        $this->init();
        $this->_title($this->__('Products With Integration Errors'));
        $this->_setActiveMenu('bseller/bseller_skyhub/queues/error_products');
        
        $this->renderLayout();
    }

}
