<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
 
class BSeller_SkyHub_Model_Cron_Sales_Order extends BSeller_SkyHub_Model_Cron_Sales_Abstract
{

    /**
     * @param Mage_Cron_Model_Schedule $schedule
     */
    public function syncAllOrders(Mage_Cron_Model_Schedule $schedule)
    {
        $orders = (array) $this->getOrderIntegrator()->orders();

        foreach ($orders as $orderData) {
            /** @var Mage_Sales_Model_Order $order */
            $order = $this->getOrderProcessor()->createOrder($orderData);

            if (!$order || !$order->getId()) {
                continue;
            }

            $statusType  = $this->arrayExtract($orderData, 'status/type');
            $statusCode  = $this->arrayExtract($orderData, 'status/code');
            // $statusLabel = $this->arrayExtract($orderData, 'status/label');

            $this->getOrderStatusProcessor()->processOrderStatus($statusCode, $statusType, $order);

            $message  = $schedule->getMessages();

            if ($order->getData('is_created')) {
                $message .= $this->__('Order ID %s was successfully created.', $order->getIncrementId());
            } elseif ($order->hasDataChanges()) {
                $message .= $this->__('Order ID %s was updated.', $order->getIncrementId());
            }

            $schedule->setMessages($message);
        }
    }
    
    
    /**
     * @return bool
     */
    protected function canRun()
    {
        if (!$this->isCronSalesOrderEnabled()) {
            return false;
        }
        
        return parent::canRun();
    }

}
