<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Jefferson Porto <jefferson.porto@e-smart.com.br>
 */
trait BSeller_SkyHub_Trait_Address
{
    /**
     * @var array
     */
    protected $_magazine = array(
        'magazine luiza'
    );

    /**
     * @param $address
     * @param $channel
     */
    public function treatAddressByChannel($address, $channel)
    {
        if (empty($channel)) {
            return;
        }

        $channel = $this->_prepareString($channel);
        if (in_array($channel, $this->_magazine)) {
            $this->_treatAddressToMagazineLuiza($address, $channel);
        }
    }

    /**
     * @param $address
     */
    protected function _treatAddressToMagazineLuiza($address)
    {
        $address->setComplement($address->getDetail());
    }

    /**
     * @param $string
     *
     * @return string
     */
    protected function _prepareString($string)
    {
        return trim(strtolower($string));
    }
}