<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Customer
{
    
    
    /**
     * @param string $fullname
     *
     * @return Varien_Object
     */
    protected function breakName($fullname)
    {
        $fullnametmp = (array) explode(' ', $fullname);
    
        $firstname  = ucwords(array_shift($fullnametmp));
        $lastname   = ucwords(array_pop($fullnametmp));
        if(!$lastname) {
            $lastname = $firstname;
        }
        $middlename = ucwords(implode(' ', $fullnametmp));
        
        return new Varien_Object([
            'firstname' => $firstname,
            'middlename' => $middlename,
            'lastname' => $lastname,
            'fullname' => $fullname,
        ]);
    }

}
