<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Queue
{

    /**
     * @param int|array     $entityIds
     * @param string        $entityType
     * @param bool          $canProcess
     * @param null|string   $processAfter
     * @param int           $storeId
     *
     * @return $this
     */
    protected function queue($entityIds, $entityType, $canProcess = true, $processAfter = null, $storeId = 0)
    {
        /** @var BSeller_SkyHub_Model_Resource_Queue $resource */
        $resource = Mage::getResourceSingleton('bseller_skyhub/queue');
        $resource->queue($entityIds, $entityType, $canProcess, $processAfter, $storeId);

        return $this;
    }


    /**
     * @return BSeller_SkyHub_Model_Resource_Queue
     */
    protected function getQueueResource()
    {
        return Mage::getResourceModel('bseller_skyhub/queue');
    }
}
