<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

trait BSeller_SkyHub_Trait_Service
{

    /**
     * @return BSeller_SkyHub_Model_Service
     */
    public function service()
    {
        return Mage::getModel('bseller_skyhub/service');
    }


    /**
     * @return \SkyHub\Api
     */
    public function api()
    {
        return $this->service()->api();
    }

}
