<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Block_Adminhtml_Widget_Grid_Container extends BSeller_Core_Block_Adminhtml_Widget_Grid_Container
{

    protected $_blockGroup = 'bseller_skyhub';


    public function __construct()
    {
        parent::__construct();
        $this->removeButton('add');
    }
}
