<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

/**
 * @method $this setSkyhubCode(string $code)
 * @method $this setSkyhubLabel(string $label)
 * @method $this setSkyhubDescription(string $description)
 * @method $this setAttributeId(int $id)
 * @method $this setEditable(bool $flag)
 * @method $this setCastType(string $type)
 * @method $this setBackendType(string $type)
 *
 * @method string getSkyhubCode()
 * @method string getSkyhubLabel()
 * @method string getSkyhubDescription()
 * @method int    getAttributeId()
 * @method bool   getEditable()
 * @method string getCastType()
 * @method string getBackendType()
 */
class BSeller_SkyHub_Model_Catalog_Product_Attributes_Mapping extends BSeller_Core_Model_Abstract
{
    
    const DATA_TYPE_STRING   = 'string';
    const DATA_TYPE_BOOLEAN  = 'boolean';
    const DATA_TYPE_DECIMAL  = 'decimal';
    const DATA_TYPE_INTEGER  = 'integer';

    const INPUT_TYPE_TEXT        = 'text';
    const INPUT_TYPE_SELECT      = 'select';
    const INPUT_TYPE_MULTISELECT = 'multiselect';

    
    public function _construct()
    {
        $this->_init('bseller_skyhub/catalog_product_attributes_mapping');
    }
    
    
    /**
     * @return bool|Mage_Eav_Model_Entity_Attribute
     */
    public function getAttribute()
    {
        if (!$this->getAttributeId()) {
            return false;
        }
        
        if ($this->hasData('attribute')) {
            return $this->getData('attribute');
        }
    
        /** @var Mage_Eav_Model_Entity_Attribute $attribute */
        $attribute = Mage::getModel('eav/entity_attribute')->load((int) $this->getAttributeId());
        $this->setData('attribute', $attribute);
        
        return $attribute;
    }


    /**
     * @return string
     */
    public function getSkyhubLabelTranslated()
    {
        return $this->__($this->getSkyhubLabel());
    }


    /**
     * @return string
     */
    public function getInputType()
    {
        $type = $this->getData('input_type');

        if (!$type || !in_array($type, $this->getValidInputTypes())) {
            $type = self::INPUT_TYPE_TEXT;
        }

        return $type;
    }


    /**
     * @return string
     */
    public function getDataType()
    {
        $type = $this->getCastType();

        if (!$type || !in_array($type, $this->getValidDataTypes())) {
            $type = self::INPUT_TYPE_TEXT;
        }

        return $type;
    }


    /**
     * @return array
     */
    protected function getValidInputTypes()
    {
        return [
            self::INPUT_TYPE_TEXT,
            self::INPUT_TYPE_MULTISELECT,
            self::INPUT_TYPE_SELECT,
        ];
    }


    /**
     * @return array
     */
    protected function getValidDataTypes()
    {
        return [
            self::DATA_TYPE_BOOLEAN,
            self::DATA_TYPE_DECIMAL,
            self::DATA_TYPE_INTEGER,
            self::DATA_TYPE_STRING,
        ];
    }
}
