<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

/**
 * Class BSeller_SkyHub_Model_Queue_Product
 */
class BSeller_SkyHub_Model_Queue_Product extends BSeller_Core_Model_Abstract
{
    use BSeller_SkyHub_Model_Integrator_Catalog_Product_Validation;
    use BSeller_SkyHub_Trait_Queue;
    use BSeller_SkyHub_Trait_Config;

    /**
     * @param $product
     * @param Mage_Core_Model_Store|null $store
     */
    public function addToQueue($product, Mage_Core_Model_Store $store = null)
    {
        $parentIds = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($product->getId());
        foreach ($parentIds as $id) {
            $this->addToQueue(Mage::getModel('catalog/product')->load($id), $store);
        }

        if (!$this->canIntegrateProduct($product, false, $store)) {
            return false;
        }

        $queueResource = $this->getQueueResource();
        /**
         * put the product on the line
         */
        $queueResource->queue(
            array(
                $product->getId()
            ),
            BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT,
            BSeller_SkyHub_Model_Queue::PROCESS_TYPE_EXPORT
        );
        return true;
    }

    /**
     * Execute queue
     *
     * @param array $queueIds
     * @return void
     */
    public function executeQueues($queueIds, Mage_Core_Model_Store $store)
    {
        $productIds = (array) $this->getQueueResource()->getEntityIdsByQueuesIds($queueIds);
        $productIds = array_filter($productIds, function (&$value) {
            $value = (int) $value;
            return $value;
        });

        /** @var Mage_Catalog_Model_Resource_Product_Collection $collection */
        $collection = $this->getProductCollection()
            ->addFieldToFilter('entity_id', array('in' => $productIds));

        if (!$collection->getSize()) {
            if ($this->isLogEnabled() && $productIds) {
                Mage::log(
                    $this->__(
                        'ERROR IN EXECUTE QUEUE: Products not exist in dataBase. IDs: %s',
                        implode('|', $productIds)
                    ),
                    null,
                    'queue_' . $this->getLogFilename()
                );
            }
            return false;
        }

        /** @var Mage_Catalog_Model_Product $product */
        foreach ($collection as $product) {
            /** @var \SkyHub\Api\Handler\Response\HandlerInterface $response */
            $response = $this->catalogProductIntegrator()->createOrUpdate($product, $store);
            if ($response === false) {
                if ($this->isLogEnabled()) {
                    Mage::log(
                        $this->__(
                            'ERROR IN EXECUTE QUEUE: Error in request with API of skyhub. SKU %s',
                            $product->getSku()
                        ),
                        null,
                        'queue_' . $this->getLogFilename()
                    );
                }
                continue;
            }

            $this->getQueueResource()->removeFromQueue(
                array($product->getId()),
                BSeller_SkyHub_Model_Entity::TYPE_CATALOG_PRODUCT
            );
        }
        return true;
    }

    /**
     * @return BSeller_SkyHub_Model_Resource_Queue
     */
    protected function getQueueResource()
    {
        /** @var BSeller_SkyHub_Model_Resource_Queue $resource */
        $resource = Mage::getResourceModel('bseller_skyhub/queue');
        return $resource;
    }

    /**
     * @return BSeller_SkyHub_Model_Resource_Catalog_Product_Collection
     */
    protected function getProductCollection()
    {
        /** @var BSeller_SkyHub_Model_Resource_Catalog_Product_Collection $collection */
        $collection = Mage::getResourceModel('bseller_skyhub/catalog_product_collection');
        return $collection;
    }

    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Product
     */
    protected function catalogProductIntegrator()
    {
        /** @var BSeller_SkyHub_Model_Integrator_Catalog_Product $integrator */
        $integrator = Mage::getSingleton('bseller_skyhub/integrator_catalog_product');
        return $integrator;
    }
}
