<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Model_Entity extends BSeller_Core_Model_Abstract
{

    const TYPE_CATALOG_PRODUCT_ATTRIBUTE = 'catalog_product_attribute';
    const TYPE_CATALOG_PRODUCT           = 'catalog_product';
    const TYPE_CATALOG_CATEGORY          = 'catalog_category';
    const TYPE_SALES_ORDER               = 'sales_order';


    protected function _construct()
    {
        $this->_init('bseller_skyhub/entity');
    }

}
