<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
require_once '/Users/tiagosampaio/Sites/e-smart/skyhub/sdk/src/bootstrap.php';

class BSeller_SkyHub_Model_Observer
{
    
    public function init(Varien_Event_Observer $observer)
    {
        $baseUri = 'https://api.skyhub.com.br';
        $email = 'valdir.calixto@e-smart.com.br';
        $apiKey = 'wxVMVTkf_csx17LioTjY';
        $apiToken = 'bZa6Ml0zgS';
    
        $api = new \SkyHub\Api($baseUri, $email, $apiKey, $apiToken);
        
        /**
         * Attribute Creation and Update.
         */
        $responseCreate = $api->productAttribute()->create('size_jeffinho', 'Size Jeffinho', ['Blue', 'White', 'Green', 'Yellow']);
    }

}
