<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class BSeller_SkyHub_Model_Observer
{

    use BSeller_SkyHub_Trait_Processors;


    /**
     * @param Varien_Event_Observer $observer
     */
    public function updateProductAttribute(Varien_Event_Observer $observer)
    {
        /** @var Mage_Catalog_Model_Resource_Eav_Attribute $attribute */
        $attribute = $observer->getData('attribute');

        if (!$attribute instanceof Mage_Catalog_Model_Resource_Eav_Attribute) {
            return;
        }

        /** @var BSeller_SkyHub_Model_Processor_Catalog_Product_Attribute $processor */
        $processor = $this->catalogProductAttributeProcessor();

        /**
         * Call method according to product attribute's operation: update or creation.
         */
        if ($attribute->getOrigData('attribute_code')) {
            /** Attribute is being updated. */
            $processor->update($attribute);
            return;
        }

        /** Otherwise attribute is being created. */
        $processor->create($attribute);
    }
}
