<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

/**
 * Class BSeller_SkyHub_Model_Plp
 *
 * @method $this setBsellerSkyhubCode(integer $entityId)
 * @method $this setExpirationDate(string $datetime)
 *
 * @method int     getBsellerSkyhubCode()
 * @method string  getExpirationDate()
 */
class BSeller_SkyHub_Model_Plp extends BSeller_Core_Model_Abstract
{

    protected function _construct()
    {
        $this->_init('bseller_skyhub/plp');
    }

}
