<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Test_Model_Processor extends EcomDev_PHPUnit_Test_Case
{

    use BSeller_SkyHub_Trait_Integrators;


    /**
     * @test
     *
     * @throws Mage_Core_Model_Store_Exception
     */
    public function checkIfTheCurrentStoreIsTheDefaultStoreWhenProcessorStarts()
    {
        /** @var BSeller_SkyHub_Model_Processor_Catalog_Product_Attribute $processor */
        $processor = $this->catalogProductAttributeProcessor();
        $this->assertInstanceOf(BSeller_SkyHub_Model_Processor_Catalog_Product_Attribute::class, $processor);
        $this->assertEquals(Mage::app()->getDefaultStoreView()->getCode(), Mage::app()->getStore()->getCode());
    }

}
