<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

class BSeller_SkyHub_Test_Model_Service extends EcomDev_PHPUnit_Test_Case
{

    use BSeller_SkyHub_Trait_Service;


    /**
     * @test
     */
    public function checkInstanceGettersAreCorrect()
    {
        $this->assertInstanceOf(BSeller_SkyHub_Model_Service::class, $this->service());
        $this->assertInstanceOf(\SkyHub\Api::class, $this->service()->api());
        $this->assertInstanceOf(\SkyHub\Api\Service\ServiceInterface::class, $this->service()->apiService());
    }

}
